name: rct
description: A minimal Flutter app created to match the provided repository structure.
publish_to: 'none'

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: '>=2.5.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.0.0
  fl_chart: ^0.63.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_dnd: ^0.1.4+1 # resolved working version


dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.13

flutter:
  uses-material-design: true

dependency_overrides:
  flutter_dnd:
    path: local_packages/flutter_dnd
